# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: test
data:
  AUTH0_ISSUER: "https://dev-azc01prw4eobuwzb.us.auth0.com"
  AUTH0_USERINFO_URL: "https://dev-azc01prw4eobuwzb.us.auth0.com/userinfo"
  ELASTICSEARCH_PASSWORD: "DkIedPPSCb"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  POSTGRES_DB: "prototype1"
  POSTGRES_PASSWORD: "avizva9372"
  POSTGRES_URL: "postgres"
  POSTGRES_USER: "postgres"
  HOST_URL: "host.docker.internal"
  STRIPE_API_KEY: "pk_test_51OwjfYD1K0859Fww6dybx2YN4PxIpcxA72z5KbauPY0B7KyPTQuwQ8imXAvsXa1LJbZtoHrjfsqXcNeNH5QZS17C00HRVKsbO9"