apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: prod
  labels:
    app: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: imenmettichi/ecomm-ui_prod
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: test
spec:
  type: NodePort
  ports:
    - nodePort: 30005
      port: 80
      targetPort: 80
  selector:
    app: ui